# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b972d5bc80c0a71113045a71b5597fcd622745fa4df8c4dff845e01ca8896f9522fe2d88561c9e74f20f8e6a111509e6ba172cc969531284a958d5f48feaa8e8

test:
  secret_key_base: d66897fd1475f30a8267fdbee004fa3043fd3dbea10277b45f684ea31c0d5d7a501c2b60959dc1be1da72ab6b0fd687f9962d970d7ba49b66bd479c8763a5c6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
